- name: loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: {{ item }}
      state: latest
    loop:
    - nginx
    - mysql
    - python